# Generated by Django 3.2.3 on 2021-06-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quest',
            new_name='text',
        ),
    ]
