# Generated by Django 3.2.3 on 2021-05-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_survey_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_at',
        ),
    ]
